exports.eligibleNationalities = [
  "ALBANIA",
  "ANDORRA",
  "ANGOLA",
  "ANGUILLA",
  "ANTIGUA AND BARBUDA",
  "ARGENTINA",
  "ARMENIA",
  "ARUBA",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIJAN",
  "BAHAMAS",
  "BARBADOS",
  "BELGIUM",
  "BELIZE",
  "BOLIVIA",
  "BOSNIA AND HERZEGOVINA",
  "BOTSWANA",
  "BRAZIL",
  "BRUNEI",
  "BULGARIA",
  "BURUNDI",
  "CAMBODIA",
  "CAMEROON",
  "CANADA",
  "CAPE VERDE",
  "CAYMAN ISLANDS",
  "CHILE",
  "CHINA-CHINA",
  "CHINA- SAR HONGKONG",
  "CHINA- SAR MACAU",
  "COLOMBIA",
  "COMOROS",
  "COOK ISLANDS",
  "COSTA RICA",
  "COTE D IVOIRE",
  "CROATIA",
  "CUBA",
  "CYPRUS",
  "CZECH REPUBLIC",
  "DENMARK",
  "DJIBOUTI",
  "DOMINICA",
  "DOMINICAN REPUBLIC",
  "EAST TIMOR (DEMOCRATIC REPUBLIC OF)",
  "ECUADOR",
  "EL SALVADOR",
  "ERITREA",
  "ESTONIA",
  "FIJI",
  "FINLAND",
  "FRANCE",
  "GABON",
  "GAMBIA",
  "GEORGIA",
  "GERMANY",
  "GHANA",
  "GREECE",
  "GRENADA",
  "GUATEMALA",
  "GUINEA",
  "GUYANA",
  "HAITI",
  "HONDURAS",
  "HUNGARY",
  "ICELAND",
  "INDONESIA",
  "IRAN",
  "IRELAND",
  "ISRAEL",
  "ITALY",
  "JAMAICA",
  "JAPAN",
  "JORDAN",
  "KAZAKHSTAN",
  "KENYA",
  "KIRIBATI",
  "KYRGYZSTAN",
  "LAOS",
  "LATVIA",
  "LESOTHO",
  "LIBERIA",
  "LIECHTENSTEIN",
  "LITHUANIA",
  "LUXEMBOURG",
  "MADAGASCAR",
  "MALAWI",
  "MALAYSIA",
  "MALI",
  "MALTA",
  "MARSHALL ISLANDS",
  "MAURITIUS",
  "MEXICO",
  "MICRONESIA (FEDERATED STATES OF)",
  "MOLDOVA",
  "MONACO",
  "MONGOLIA",
  "MONTENEGRO",
  "MONTSERRAT",
  "MOZAMBIQUE",
  "MYANMAR",
  "NAMIBIA",
  "NAURU",
  "NETHERLANDS",
  "NEW ZEALAND",
  "NICARAGUA",
  "NIGER",
  "NIUE ISLAND",
  "NORWAY",
  "OMAN",
  "PALAU",
  "PALESTINE",
  "PANAMA",
  "PAPUA NEW GUINEA",
  "PARAGUAY",
  "PERU",
  "PHILIPPINES",
  "POLAND",
  "PORTUGAL",
  "QATAR",
  "REPUBLIC OF KOREA",
  "REPUBLIC OF MACEDONIA",
  "ROMANIA",
  "RUSSIAN FEDERATION",
  "RWANDA",
  "SAINT KITTS AND NEVIS",
  "SAINT LUCIA",
  "SAINT VINCENT AND THE GRENADINES",
  "SAMOA",
  "SAN MARINO",
  "SAUDI ARABIA",
  "SENEGAL",
  "SERBIA",
  "SEYCHELLES",
  "SIERRA LEONE",
  "SINGAPORE",
  "SLOVAKIA",
  "SLOVENIA",
  "SOLOMON ISLANDS",
  "SOUTH AFRICA",
  "SPAIN",
  "SRI LANKA",
  "SURINAME",
  "SWAZILAND",
  "SWEDEN",
  "SWITZERLAND",
  "TAIWAN",
  "TAJIKISTAN",
  "TANZANIA",
  "THAILAND",
  "TONGA",
  "TRINIDAD AND TOBAGO",
  "TURKS AND CAICOS ISL",
  "TUVALU",
  "UGANDA",
  "UKRAINE",
  "UNITED ARAB EMIRATES",
  "UNITED KINGDOM",
  "UNITED STATES OF AMERICA",
  "URUGUAY",
  "UZBEKISTAN",
  "VANUATU",
  "VATICAN CITY STATE ( HOLY SEE)",
  "VENEZUELA",
  "VIETNAM",
  "ZAMBIA",
  "ZIMBABWE",
];
const allNationalities = [
  { value: "AFG", country: "AFGHANISTAN" },
  { value: "ALA", country: "ALAND ISLANDS" },
  { value: "ALB", country: "ALBANIA" },
  { value: "DZA", country: "ALGERIA" },
  { value: "ASM", country: "AMERICAN SAMOA" },
  { value: "AND", country: "ANDORRA" },
  { value: "AGO", country: "ANGOLA" },
  { value: "AIA", country: "ANGUILLA" },
  { value: "ATA", country: "ANTARTICA" },
  { value: "ATG", country: "ANTIGUA AND BARBUDA" },
  { value: "ARG", country: "ARGENTINA" },
  { value: "ARM", country: "ARMENIA" },
  { value: "ABW", country: "ARUBA" },
  { value: "AUS", country: "AUSTRALIA" },
  { value: "AUT", country: "AUSTRIA" },
  { value: "AZE", country: "AZERBAIJAN" },
  { value: "BHS", country: "BAHAMAS" },
  { value: "BHR", country: "BAHRAIN" },
  { value: "BGD", country: "BANGLADESH" },
  { value: "BRB", country: "BARBADOS" },
  { value: "BLR", country: "BELARUS" },
  { value: "BEL", country: "BELGIUM" },
  { value: "BLZ", country: "BELIZE" },
  { value: "BEN", country: "BENIN" },
  { value: "BMU", country: "BERMUDA" },
  { value: "BTN", country: "BHUTAN" },
  { value: "BOL", country: "BOLIVIA" },
  { value: "BIH", country: "BOSNIA AND HERZEGOVINA" },
  { value: "BWA", country: "BOTSWANA" },
  { value: "BVT", country: "BOUVET ISLAND" },
  { value: "BRA", country: "BRAZIL" },
  { value: "IOT", country: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "BRN", country: "BRUNEI" },
  { value: "BGR", country: "BULGARIA" },
  { value: "BFA", country: "BURKINA FASO" },
  { value: "BDI", country: "BURUNDI" },
  { value: "KHM", country: "CAMBODIA" },
  { value: "CMR", country: "CAMEROON" },
  { value: "CAN", country: "CANADA" },
  { value: "CPV", country: "CAPE VERDE" },
  { value: "XCC", country: "CARRIBEAN COMMUNITY" },
  { value: "CYM", country: "CAYMAN ISLANDS" },
  { value: "CAF", country: "CENTRAL AFRICAN REPUBLIC" },
  { value: "TCD", country: "CHAD" },
  { value: "CHL", country: "CHILE" },
  { value: "CHN", country: "CHINA-CHINA" },
  { value: "HKG", country: "CHINA- SAR HONGKONG" },
  { value: "MAC", country: "CHINA- SAR MACAU" },
  { value: "CXR", country: "CHRISTMAS ISLANDS" },
  { value: "CCK", country: "COCOS (KEELING) ISLANDS" },
  { value: "COL", country: "COLOMBIA" },
  { value: "COM", country: "COMOROS" },
  { value: "COG", country: "CONGO" },
  { value: "COD", country: "CONGO (DEMOCRATIC REPUBLIC OF)" },
  { value: "COK", country: "COOK ISLANDS" },
  { value: "CRI", country: "COSTA RICA" },
  { value: "CIV", country: "COTE D IVOIRE" },
  { value: "HRV", country: "CROATIA" },
  { value: "CUB", country: "CUBA" },
  { value: "CYP", country: "CYPRUS" },
  { value: "CZE", country: "CZECH REPUBLIC" },
  { value: "PRK", country: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA" },
  { value: "DNK", country: "DENMARK" },
  { value: "DJI", country: "DJIBOUTI" },
  { value: "DMA", country: "DOMINICA" },
  { value: "DOM", country: "DOMINICAN REPUBLIC" },
  { value: "TLS", country: "EAST TIMOR (DEMOCRATIC REPUBLIC OF)" },
  { value: "ECU", country: "ECUADOR" },
  { value: "EGY", country: "EGYPT" },
  { value: "SLV", country: "EL SALVADOR" },
  { value: "GNQ", country: "EQUATORIAL GUINEA" },
  { value: "ERI", country: "ERITREA" },
  { value: "EST", country: "ESTONIA" },
  { value: "ETH", country: "ETHIOPIA" },
  { value: "FLK", country: "FALKLAND ISLANDS (MALVINES)" },
  { value: "FRO", country: "FAROE ISLANDS" },
  { value: "FJI", country: "FIJI" },
  { value: "FIN", country: "FINLAND" },
  { value: "FRA", country: "FRANCE" },
  { value: "FXX", country: "FRANCE METROPOLITAN" },
  { value: "GUF", country: "FRENCH GUIANA" },
  { value: "PYF", country: "FRENCH POLYNESIA" },
  { value: "ATF", country: "FRENCH SOUTHERN TERRITORIES" },
  { value: "GAB", country: "GABON" },
  { value: "GMB", country: "GAMBIA" },
  { value: "GEO", country: "GEORGIA" },
  { value: "DEU", country: "GERMANY" },
  { value: "GHA", country: "GHANA" },
  { value: "GIB", country: "GIBRALTAR" },
  { value: "GRC", country: "GREECE" },
  { value: "GRL", country: "GREENLAND" },
  { value: "GRD", country: "GRENADA" },
  { value: "GLP", country: "GUADELOUPE" },
  { value: "GUM", country: "GUAM" },
  { value: "GTM", country: "GUATEMALA" },
  { value: "GGY", country: "GUERNSEY" },
  { value: "GIN", country: "GUINEA" },
  { value: "GNB", country: "GUINEA-BISSAU" },
  { value: "GUY", country: "GUYANA" },
  { value: "HTI", country: "HAITI" },
  { value: "HMD", country: "HEARD AND MCDONALD ISLANDS" },
  { value: "HND", country: "HONDURAS" },
  { value: "HUN", country: "HUNGARY" },
  { value: "ISL", country: "ICELAND" },
  { value: "IDN", country: "INDONESIA" },
  { value: "IRN", country: "IRAN" },
  { value: "IRQ", country: "IRAQ" },
  { value: "IRL", country: "IRELAND" },
  { value: "IMN", country: "ISLE OF MAN" },
  { value: "ISR", country: "ISRAEL" },
  { value: "ITA", country: "ITALY" },
  { value: "JAM", country: "JAMAICA" },
  { value: "JPN", country: "JAPAN" },
  { value: "JEY", country: "JERSEY" },
  { value: "JOR", country: "JORDAN" },
  { value: "KAZ", country: "KAZAKHSTAN" },
  { value: "KEN", country: "KENYA" },
  { value: "KIR", country: "KIRIBATI" },
  { value: "KWT", country: "KUWAIT" },
  { value: "KGZ", country: "KYRGYZSTAN" },
  { value: "LAO", country: "LAOS" },
  { value: "LVA", country: "LATVIA" },
  { value: "LBN", country: "LEBANON" },
  { value: "LSO", country: "LESOTHO" },
  { value: "LBR", country: "LIBERIA" },
  { value: "LBY", country: "LIBYA" },
  { value: "LIE", country: "LIECHTENSTEIN" },
  { value: "LTU", country: "LITHUANIA" },
  { value: "LUX", country: "LUXEMBOURG" },
  { value: "MDG", country: "MADAGASCAR" },
  { value: "MWI", country: "MALAWI" },
  { value: "MYS", country: "MALAYSIA" },
  { value: "MDV", country: "MALDIVES" },
  { value: "MLI", country: "MALI" },
  { value: "MLT", country: "MALTA" },
  { value: "MHL", country: "MARSHALL ISLANDS" },
  { value: "MTQ", country: "MARTINIQUE" },
  { value: "MRT", country: "MAURITANIA" },
  { value: "MUS", country: "MAURITIUS" },
  { value: "MYT", country: "MAYOTTE" },
  { value: "MEX", country: "MEXICO" },
  { value: "FSM", country: "MICRONESIA (FEDERATED STATES OF)" },
  { value: "MDA", country: "MOLDOVA" },
  { value: "MCO", country: "MONACO" },
  { value: "MNG", country: "MONGOLIA" },
  { value: "MNE", country: "MONTENEGRO" },
  { value: "MSR", country: "MONTSERRAT" },
  { value: "MAR", country: "MOROCCO" },
  { value: "MOZ", country: "MOZAMBIQUE" },
  { value: "MMR", country: "MYANMAR" },
  { value: "NAM", country: "NAMIBIA" },
  { value: "NRU", country: "NAURU" },
  { value: "NPL", country: "NEPAL" },
  { value: "NLD", country: "NETHERLANDS" },
  { value: "ANT", country: "NETHERLANDS ANTILLES" },
  { value: "NTZ", country: "NEUTRAL ZONE" },
  { value: "NCL", country: "NEW CALEDONIA" },
  { value: "NZL", country: "NEW ZEALAND" },
  { value: "NIC", country: "NICARAGUA" },
  { value: "NER", country: "NIGER" },
  { value: "NGA", country: "NIGERIA" },
  { value: "NIU", country: "NIUE ISLAND" },
  { value: "NFK", country: "NORFOLK ISLAND" },
  { value: "MNP", country: "NORTHERN MARIANA ISLANDS" },
  { value: "NOR", country: "NORWAY" },
  { value: "OMN", country: "OMAN" },
  { value: "OTH", country: "OTHERS" },
  { value: "PAK", country: "PAKISTAN" },
  { value: "PLW", country: "PALAU" },
  { value: "PSE", country: "PALESTINE" },
  { value: "PAN", country: "PANAMA" },
  { value: "PNG", country: "PAPUA NEW GUINEA" },
  { value: "PRY", country: "PARAGUAY" },
  { value: "XXX", country: "PERSON OF UNSPECIFIED NATIONALITY" },
  { value: "PER", country: "PERU" },
  { value: "PHL", country: "PHILIPPINES" },
  { value: "PCN", country: "PITCAIRN" },
  { value: "POL", country: "POLAND" },
  { value: "PRT", country: "PORTUGAL" },
  { value: "PRI", country: "PUERTO RICO" },
  { value: "QAT", country: "QATAR" },
  { value: "XXB", country: "REFUGEE" },
  { value: "XXC", country: "REFUGEE(NON-CONVENTIONAL)" },
  { value: "KOR", country: "REPUBLIC OF KOREA" },
  { value: "MKD", country: "REPUBLIC OF MACEDONIA" },
  { value: "UNK", country: "RESIDENT OF KOSOVO (UNMIK)" },
  { value: "REU", country: "REUNION" },
  { value: "ROU", country: "ROMANIA" },
  { value: "RUS", country: "RUSSIAN FEDERATION" },
  { value: "RWA", country: "RWANDA" },
  { value: "SHN", country: "SAINT HELENA" },
  { value: "KNA", country: "SAINT KITTS AND NEVIS" },
  { value: "LCA", country: "SAINT LUCIA" },
  { value: "SPM", country: "SAINT PIERRE AND MIQUELON" },
  { value: "VCT", country: "SAINT VINCENT AND THE GRENADINES" },
  { value: "WSM", country: "SAMOA" },
  { value: "SMR", country: "SAN MARINO" },
  { value: "STP", country: "SAO TOME AND PRINCIPE" },
  { value: "SAU", country: "SAUDI ARABIA" },
  { value: "SEN", country: "SENEGAL" },
  { value: "SRB", country: "SERBIA" },
  { value: "SYC", country: "SEYCHELLES" },
  { value: "SLE", country: "SIERRA LEONE" },
  { value: "SGP", country: "SINGAPORE" },
  { value: "SVK", country: "SLOVAKIA" },
  { value: "SVN", country: "SLOVENIA" },
  { value: "SLB", country: "SOLOMON ISLANDS" },
  { value: "SOM", country: "SOMALIA" },
  { value: "ZAF", country: "SOUTH AFRICA" },
  { value: "SGS", country: "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS" },
  { value: "SSD", country: "SOUTH SUDAN" },
  { value: "XOM", country: "SOVEREIGN MILITARY ORDER OF MALTA" },
  { value: "ESP", country: "SPAIN" },
  { value: "LKA", country: "SRI LANKA" },
  { value: "XXA", country: "STATELESS" },
  { value: "SDN", country: "SUDAN" },
  { value: "SUR", country: "SURINAME" },
  { value: "SJM", country: "SVALBARD AND JAN MAYEN ISLANDS" },
  { value: "SWZ", country: "SWAZILAND" },
  { value: "SWE", country: "SWEDEN" },
  { value: "CHE", country: "SWITZERLAND" },
  { value: "SYR", country: "SYRIAN ARAB REPUBLIC" },
  { value: "TWN", country: "TAIWAN" },
  { value: "TJK", country: "TAJIKISTAN" },
  { value: "TZA", country: "TANZANIA" },
  { value: "THA", country: "THAILAND" },
  { value: "TBT", country: "TIBET" },
  { value: "TGO", country: "TOGO" },
  { value: "TKL", country: "TOKELAU" },
  { value: "TON", country: "TONGA" },
  { value: "TTO", country: "TRINIDAD AND TOBAGO" },
  { value: "TUN", country: "TUNISIA" },
  { value: "TUR", country: "TURKEY" },
  { value: "TKM", country: "TURKMENISTAN" },
  { value: "TCA", country: "TURKS AND CAICOS ISL" },
  { value: "TUV", country: "TUVALU" },
  { value: "UGA", country: "UGANDA" },
  { value: "GBD", country: "UK BRITISH DEPENDENT TERRITORIES CITIZEN" },
  { value: "GBN", country: "UK BRITISH NATIONAL(OVERSEES)" },
  { value: "GBO", country: "UK BRITISH OVERSEES CITIZEN" },
  { value: "GBP", country: "UK BRITISH PROTECTED PERSON" },
  { value: "GBS", country: "UK BRITISH SUBJECT" },
  { value: "UKR", country: "UKRAINE" },
  { value: "ARE", country: "UNITED ARAB EMIRATES" },
  { value: "GBR", country: "UNITED KINGDOM" },
  { value: "UNO", country: "UNITED NATIONS ORGANIZATION" },
  { value: "UNA", country: "UNITED NATIONS SPECIALIZED AGENCY" },
  { value: "UMI", country: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { value: "USA", country: "UNITED STATES OF AMERICA" },
  { value: "URY", country: "URUGUAY" },
  { value: "UZB", country: "UZBEKISTAN" },
  { value: "VUT", country: "VANUATU" },
  { value: "VAT", country: "VATICAN CITY STATE ( HOLY SEE)" },
  { value: "VEN", country: "VENEZUELA" },
  { value: "VNM", country: "VIETNAM" },
  { value: "VGB", country: "VIRGIN ISLANDS (BRITISH)" },
  { value: "VIR", country: "VIRGIN ISLANDS (US)" },
  { value: "WLF", country: "WALLIS AND FUTUNA ISLANDS" },
  { value: "ESH", country: "WESTERN SAHARA" },
  { value: "YEM", country: "YEMEN" },
  { value: "YUG", country: "YUGOSLAVIA" },
  { value: "ZMB", country: "ZAMBIA" },
  { value: "ZWE", country: "ZIMBABWE" },
];

exports.countriesWithConsulate = [
  "AFGHANISTAN",
  "ALGERIA",
  "ANGOLA",
  "ARGENTINA",
  "ARMENIA",
  "AUSTRALIA",
  "AUSTRIA",
  "AZERBAIJAN",
  "BAHRAIN",
  "BELARUS",
  "BELGIUM",
  "BHUTAN",
  "BOTSWANA",
  "BRAZIL",
  "BRUNEI",
  "BULGARIA",
  "CAMBODIA",
  "CANADA",
  "CHILE",
  "CHINA-CHINA",
  "COLOMBIA",
  "CONGO (DEMOCRATIC REPUBLIC OF)",
  "COTE D IVOIRE",
  "CROATIA",
  "CUBA",
  "CYPRUS",
  "CZECH REPUBLIC",
  "DENMARK",
  "EGYPT",
  "ETHIOPIA",
  "FIJI",
  "FINLAND",
  "FRANCE",
  "GERMANY",
  "GHANA",
  "GREECE",
  "GUATEMALA",
  "HUNGARY",
  "ICELAND",
  "INDIA",
  "INDONESIA",
  "IRAN",
  "IRAQ",
  "IRELAND",
  "ISRAEL",
  "ITALY",
  "JAMAICA",
  "JAPAN",
  "JORDAN",
  "KAZAKHSTAN",
  "KENYA",
  "KUWAIT",
  "KYRGYZSTAN",
  "LAOS",
  "LATVIA",
  "LEBANON",
  "MADAGASCAR",
  "MALAWI",
  "MALAYSIA",
  "MALDIVES",
  "MALI",
  "MAURITIUS",
  "MEXICO",
  "MONGOLIA",
  "MOROCCO",
  "MOZAMBIQUE",
  "MYANMAR",
  "NAMIBIA",
  "NEPAL",
  "NETHERLANDS",
  "NEW ZEALAND",
  "NIGER",
  "NIGERIA",
  "NORWAY",
  "OMAN",
  "PAKISTAN",
  "PALESTINE",
  "PANAMA",
  "PAPUA NEW GUINEA",
  "PERU",
  "PHILIPPINES",
  "POLAND",
  "PORTUGAL",
  "QATAR",
  "REPUBLIC OF KOREA",
  "REUNION",
  "ROMANIA",
  "RUSSIAN FEDERATION",
  "SAUDI ARABIA",
  "SENEGAL",
  "SERBIA",
  "SEYCHELLES",
  "SINGAPORE",
  "SLOVAKIA",
  "SLOVENIA",
  "SOUTH AFRICA",
  "SOUTH SUDAN",
  "SPAIN",
  "SRI LANKA",
  "SUDAN",
  "SURINAME",
  "SWEDEN",
  "SWITZERLAND",
  "SYRIAN ARAB REPUBLIC",
  "TAIWAN",
  "TAJIKISTAN",
  "TANZANIA",
  "THAILAND",
  "TRINIDAD AND TOBAGO",
  "TUNISIA",
  "TURKEY",
  "TURKMENISTAN",
  "UGANDA",
  "UKRAINE",
  "UNITED ARAB EMIRATES",
  "UNITED KINGDOM",
  "UNITED STATES OF AMERICA",
  "UZBEKISTAN",
  "VENEZUELA",
  "VIETNAM",
  "YEMEN",
  "ZAMBIA",
  "ZIMBABWE",
];

exports.nations = allNationalities.map((nation) => {
  return { value: nation.value, text: nation.country };
});
